## To use docker compose to rebuild the image  
# docker compose up -d --build

version: "3.8"
services:
  mojo :
    container_name: mojo
    build :
      context: .
      dockerfile: Dockerfile.mojosdk
      args:
        - AUTH_KEY=1Auth_token
      no_cache : true
    ports:
      - 8888:8888 

    volumes:
      - ./..:/mojo
      
    working_dir: /mojo 
    