repos:
  - repo: local
    hooks:
      - id: mojo-format
        name: mojo-format
        entry: mojo format
        language: system
        files: '\.(mojo|ðŸ”¥)$'
        stages: [commit]
      - id: check-license
        name: check-license
        entry: mojo stdlib/scripts/check-licenses.mojo
        language: system
        files: '\.(mojo|ðŸ”¥|py)$'
        stages: [commit]
      - id: spellcheck-notebook
        name: Spellcheck Jupyter Notebook
        entry: ./trying_stuff.sh
        language: python
        files: \.ipynb$
        additional_dependencies:
          - jupyter==1.0.0
          - codespell==2.2.6
          - nbformat==5.10.4
