name: mojo-plotter-mac
channels:
  - pytorch
  - anaconda
dependencies:
  - blas=1.0=openblas
  - brotlipy=0.7.0=py311h80987f9_1002
  - bzip2=1.0.8=h620ffc9_4
  - ca-certificates=2023.08.22=hca03da5_0
  - certifi=2023.7.22=py311hca03da5_0
  - cffi=1.15.1=py311h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.3=py311hd4332d6_0
  - filelock=3.9.0=py311hca03da5_0
  - freetype=2.12.1=h1192e45_0
  - giflib=5.2.1=h80987f9_3
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - idna=3.4=py311hca03da5_0
  - jinja2=3.1.2=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.1=py311h80987f9_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.1=py311hca03da5_0
  - numpy=1.26.0=py311he598dae_0
  - numpy-base=1.26.0=py311hfbfe69c_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.11=h1a28f6b_2
  - pillow=10.0.1=py311h3b245a6_0
  - pip=23.2.1=py311hca03da5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.5=hb885b13_0
  - pytorch=2.1.0=py3.11_0
  - pyyaml=6.0=py311h80987f9_1
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py311hca03da5_0
  - setuptools=68.0.0=py311hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - sympy=1.11.1=py311hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - torchaudio=2.1.0=py311_cpu
  - torchvision=0.15.2=cpu_py311he74fb5d_0
  - typing_extensions=4.7.1=py311hca03da5_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py311hca03da5_0
  - wheel=0.41.2=py311hca03da5_0
  - xz=5.4.2=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
